# Generated by Django 3.2 on 2022-03-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taketime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
