# Generated by Django 3.1.1 on 2021-11-05 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=100)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='role_manager.consumerproject')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ApiUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=50)),
                ('action', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('component', models.ManyToManyField(blank=True, null=True, related_name='apiurls', to='role_manager.Component')),
                ('groups', models.ManyToManyField(blank=True, null=True, related_name='apiurls', to='auth.Group')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
