# Generated by Django 3.1.1 on 2021-11-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiurl',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apiurl',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
