# Generated by Django 3.2 on 2022-03-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosec',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
