# Generated by Django 3.2 on 2022-03-02 07:28

import auth_rest_phone.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09999999999'. Up to 11 digits allowed.", regex='^09[0-9]{9}$')])),
                ('key', models.CharField(blank=True, max_length=100)),
                ('count', models.IntegerField(default=0, help_text='Number of otp send')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('validated', models.BooleanField(default=False, help_text='IF it is true, that means user have validate otp correctly in second API')),
                ('logged', models.BooleanField(default=False, help_text='If otp verification got successful')),
                ('forget', models.BooleanField(default=False, help_text='Only true for forget password')),
                ('forget_logged', models.BooleanField(default=False, help_text='Only true if validate otp forget get successful')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09999999999'. Up to 11 digits allowed.", regex='^09[0-9]{9}$')])),
                ('email', models.CharField(max_length=150, null=True, unique=True, validators=[django.core.validators.EmailValidator(code='invalid_email')])),
                ('uid', models.CharField(max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('avatar', models.ImageField(blank=True, default='avatar/default_avatar.jpg', null=True, upload_to=auth_rest_phone.models.UserProfile.user_directory_path)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('enable_authenticator', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
